### PR TITLE
Chore/gradle plugin 8.0.1 kotlin 1.8.21

### PR DESCRIPTION
**Pull request by marcodallaba**
Hi, I thought it would help to update gradle and kotlin version. Do you think I should upgrade also source and target compatibility? Am I missing something? I'm available for any modification.

I tried to test the PR but I receive the following error: 
> Task :buildkonfig-compiler:signMavenPublication FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildkonfig-compiler:signMavenPublication'.
> Cannot perform signing task ':buildkonfig-compiler:signMavenPublication' because it has no configured signatory

Should I add something to global Gradle properties?
Thanks

### CODE REVIEW

**Comment by yshrsmz** [comment]
Hi, Thanks for the contribution!

> I tried to test the PR but I receive the following error:

what task did you run?
You should be able to run `./gradlew test` without signing configuration

**Comment by marcodallaba** [comment]
@yshrsmz thank you, I was able to run ./gradlew test successfully. Now I wonder why all checks have failed, I have run all test cases locally and all of them passed. Maybe the problem is the java version used by the GitHub action pipeline? Can you set it to Java 17? Thank you

**Comment by marcodallaba** [comment]
Great! All test passed, It could be useful for me to test the plugin locally, how I can publish it to mavenLocal?

**Comment by marcodallaba** [comment]
Great! All test passed, It could be useful for me to test the plugin locally, how I can publish it to mavenLocal? @yshrsmz

**Comment by yshrsmz** [comment]
> Do you think I should upgrade also source and target compatibility?

I'm not 100%, but I think we could bump those versions to 11.

**Comment by yshrsmz** [comment]
> Do you think I should upgrade also source and target compatibility?

I'm not 100% sure, but I think we could bump those versions to 11.

**Comment by marcodallaba** [comment]
> > Do you think I should upgrade also source and target compatibility?
> 
> I'm not 100% sure, but I think we could bump those versions to 11.

Yeah, I think it too.

Publishing is broken with gradle 8.0, I'm fixing it right now :)

**Review by yshrsmz — APPROVED** [review]
Thanks!
Let's see how it goes.

**Comment by jasonsparc** [comment]
I'm currently working on the Android & JVM support in my [fork](https://github.com/jasonsparc/BuildKonfig/tree/dev/nn), and I noticed that the versions for both AGP (Android Gradle Plugin) and the Kotlin Gradle Plugin are now higher than before. I'm not sure if that was intended but this could break builds that can't upgrade to a higher version of AGP or Kotlin Gradle Plugin. Should I fix it in my fork? Or was that intended? At the moment, I don't see any reason for them to be too high. We can keep the Gradle Wrapper version to `8.0` though, and in fact, I just bumped it to `8.0.2` (as recommended by Gradle to always update to at least the latest bugfix/patch release).

P.S. Once I'm confident with my fork, I'll open a PR.

**Comment by marcodallaba** [comment]
Hi @jasonsparc, just noticed that I should have upgraded agp to 8.0.2 and not 8.0.1 (I agree with you). I thought it was a good thing to upgrade Kotlin, gradle wrapper and plugin to fully support the new embedded idk (Java 17) of Android Studio and to take advantage of the new benefits of gradle 8.0. I'm available to do any change but in which way this PR could break builds that can't upgrade to a higher version of AGP or Kotlin Gradle Plugin?

**Comment by jasonsparc** [comment]
@marcodallaba Each AGP version has a minimum gradle version, thus upgrading AGP would also force users to upgrade their gradle wrappers, or else, the build will fail. See, https://developer.android.com/build/releases/gradle-plugin

I for example, have projects that I can't migrate to a higher gradle version, due to occasional issues, such as https://github.com/gradle/gradle/issues/25164 and many more stuffs similar to that. So sometimes, it's Gradle's fault, sometimes it's AGP, and sometimes, it's some community Gradle plugin. And in those cases, you must stay to a lower version to avoid issues introduced.

But, there are also apps that I've maintained in the past for companies I've worked with that couldn't afford to use a higher AGP version, due to so called "high migration cost" that none of the non-technical managers would even care about, even though it's worth it to migrate for the sake of better tooling support (such as with Android Studio), but they won't allow you to.

**Comment by yshrsmz** [comment]
I think we should instead encourage people(and perhaps help convince their boss) by upgrading BuildKonfig's dependencies.

**Comment by yshrsmz** [comment]
As a rule of thumb, we should:

- Support *the latest* Kotlin Multiplatform Project features
  - This is the most important thing because the library's primary focus is KMP.
- Support Android/JVM that the latest gradle KMP plugin supports

**Comment by yshrsmz** [comment]
@jasonsparc Thanks for your detailed explanation! I really appreciate it.

Your opinion is legitimate, and honestly, I don't see that many conflicts with my "rule of thumb"
  - "Rule of thumb" was not a good word choice in that case. It actually means "my rules of developing BuildKonfig"
- KMP environment is not yet stable and things can change rapidly.
  - (And users should know it)
- This lib is a gradle plugin, and it heavily relies on how KMP builds the app.
- So we should keep an eye on how it changes for each Kotlin version update.
- Thus, I choose to update the dependencies often if the conditions are met.
  - and that's why BuildKonfig is still in pre-1.0
- Once KMP becomes stable, I definitely respect compatibility more.

**Comment by guyaumetremblay** [comment]
@yshrsmz Hi! Just to be sure that I did understand well the latests comments: this plugin now required Gradle 8? Because the Readme state the version 7 and my project, using 7.5, doesn't compile when I add your plugin.

**Comment by yshrsmz** [comment]
@guyaumetremblay 
This hasn't been released yet, so the latest BuildKonfig plugin should work with Gradle 7

**Pull request merged**
